// Generated by Wrangler by running `wrangler types`

interface Env {
	REDIS_HOST: string;
	REDIS_PORT: 6379;
	REDIS_PASSWORD: string;
	MY_DURABLE_OBJECT: DurableObjectNamespace /* MyDurableObject */;
}
