#:schema node_modules/wrangler/config-schema.json
name = "worker-tcp"
main = "src/index.ts"
compatibility_date = "2024-11-12"

[observability]
enabled = true

[vars]
REDIS_HOST = "localhost"
REDIS_PORT = 6379

[[durable_objects.bindings]]
name = "MY_DURABLE_OBJECT"
class_name = "MyDurableObject"

[[migrations]]
tag = "v1"
new_classes = ["MyDurableObject"]

[env.test.vars]
REDIS_HOST = "localhost"
REDIS_PORT = 6379

[[env.test.durable_objects.bindings]]
name = "MY_DURABLE_OBJECT"
class_name = "MyDurableObject"

[[env.test.migrations]]
tag = "v1"
new_classes = ["MyDurableObject"]
